highValueTransactionLimit: 10000
customersOriginalCurrency: "INR"
foreignCurrencyHighValueAmount: 5000
duplicateTransactionTimeDurationInMinutes: 60
highSpendOnSingleMerchantTimeDurationInHours: 24
highSpendOnSingleMerchantTotalAmount: 30000